export const colors = {
  skyBlue: '#069ccd',
  whiteGray: '#f7f6f3',
  dusk: 'rgb(65,77,107)',
  green: 'rgb(29,211,168)',
  greenBlue: 'rgb(36,205,151)',
  mediumGray: 'rgb(134,154,183)',
  paleGray: 'rgb(221,226,236)',
  lightBackground: 'white',
  lightBackgroundLight: '#f7f6f3',
  darkBackground: '#323739',
  darkBackgroundLight: '#393241',
  blackRegular: '#48454D',
  dark: '#48454d',
  light: '#ffffff',
  black: '#48454d',
  black2: '#222222',
  primaryLight: '#cd9bff',
  primaryDark: '#9a77ff',
  lightGray1: '#f2f2f2',
  lightGray2: '#eaeaea',
  lightGray3: '#F0F0F0',
  lightGray4: '#f7f7f7',
  lightGray5: '#2E404C',
  lightGray6: '#c4c4c4',
  darkGray1: '#929292',
  darkGray2: '#cfced0',
  darkGray3: '#999999',
  darkGray4: '#727272',
  darkGray5: '#666666',
  positive: '#44d1a6',
  negative: '#F9A1A1',
  backgroundColorDark: '#192328',
  primary: '#67BD6B',
};

export const light = {
  background: colors.lightBackground,
  btnPrimary: colors.skyBlue,
  btnPrimaryFont: 'white',
  btnPrimaryLight: colors.whiteGray,
  btnPrimaryLightFont: 'black',
  textDisabled: '#969696',
  btnDisabled: 'rgb(224,224,224)',
  fontColor: 'black',
  tintColor: '#333333',
  headerBorder: colors.lightGray2,
  font: colors.dark,
  primary: colors.primaryLight,
  button1: colors.lightGray1,
  buttonBorder: colors.light,
  cardLoadingBackground: colors.lightGray3,
  inactivateButtonBackground: colors.lightGray1,
  inactivateButtonText: colors.darkGray3,
  skipText: colors.darkGray2,
  viewIcon: colors.darkGray2,
  collectionCardBackground: colors.lightGray4,
  whoseCollectionFont: colors.black,
  profileFont: colors.black,
  myCollectionNoDataBackground: colors.lightGray1,
  headerBorderBottom: colors.lightGray1,
  collectionCardPrivate: colors.black,
  textInTag: colors.light,
  inactiveFont: colors.darkGray2,
  boldWeightBorder: colors.black,
};

export type Theme = typeof light;

export const dark = {
  background: colors.darkBackground,
  btnPrimary: colors.skyBlue,
  btnPrimaryFont: 'white',
  btnPrimaryLight: colors.whiteGray,
  btnPrimaryLightFont: 'black',
  textDisabled: '#969696',
  btnDisabled: 'rgb(224,224,224)',
  fontColor: 'white',
  tintColor: '#a3a3a3',
  headerBorder: colors.blackRegular,
  font: colors.lightGray1,
  primary: colors.primaryDark,
  button1: 'transparent',
  buttonBorder: colors.light,
  cardLoadingBackground: colors.darkGray1,
  inactivateButtonBackground: colors.darkGray3,
  inactivateButtonText: colors.lightGray1,
  skipText: colors.darkGray3,
  viewIcon: colors.darkGray3,
  collectionCardBackground: colors.black,
  whoseCollectionFont: colors.lightGray1,
  profileFont: colors.lightGray1,
  myCollectionNoDataBackground: colors.black,
  headerBorderBottom: colors.black,
  collectionCardPrivate: colors.lightGray1,
  textInTag: colors.black,
  inactiveFont: colors.darkGray4,
  boldWeightBorder: colors.darkGray2,
};
